version: '3'
services:
  ui:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /home/jonm/repos/galvanize/mini-app-movies/frontend:/src/app

  api:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - /home/jonm/repos/galvanize/mini-app-movies/server:/src/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: